version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging to AWS ECR registry
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b6s4k0k9/javaapp
  build:
    commands:
      - echo Build the image
      - docker build -t javaapp-repo .
      - docker tag javaapp-repo:latest public.ecr.aws/b6s4k0k9/javaapp:latest
  post_build:
    commands:
      - echo push the image to ecr
      - docker push public.ecr.aws/b6s4k0k9/javaapp:latest
