pipeline {
  agent any
  environment {
    PATH = "/opt/apache-maven-3.9.0/bin:${PATH}"
  }
  stages {
    stage("git clone code") {
      steps{
        git 'https://github.com/architectdevops7/jenkins-cicd.git'
      }
    }
    
    stage("maven build code"){
      steps{
        sh 'mvn clean package'
      }
    }
    stage("maven test code"){
      steps{
        sh 'mvn test'
      }
    }
    stage("tomcat deploy code"){
      steps{
        deploy adapters: [tomcat9(credentialsId: 'tomcat-user', path: '', url: 'http://107.23.147.188:8080/')], contextPath: null, war: '**/*.war'
        }
      }
    }
  }
